### ISSUE TITLE
tv broken?

### ISSUE THREAD

**Issue by paulovieira** [hapijs/tv#102]
I made a fresh git clone & npm install. The example "simple.js" isn't working.

I can access the `/debug/console` route, but I get an empty screen. In dev tools I see that the requests to these files return 404:
```
http://localhost:8000/debug/console/css/style.css
http://localhost:8000/debug/console/js/main.js
```

I also get 404 if I use instead the uri logged to the console when the application starts, which in my case is `http://hp-novo:8000`.

**Comment by geek** [comment]
@paulovieira the hp-novo is your local hostname... if your host file isn't updated to point that to 127.0.0.1 then it won't work.  The example `simple.js` may need a little TLC.

**Comment by ugate** [comment]
I'm getting the same thing using localhost

**Comment by joseph-norman** [comment]
@ugate @paulovieira did you check out the npm scripts content? If you're cloning this repo there's a few things you'll need to do past npm install to run the local examples. In particular from the `package.json`:

```
 "build": "npm run build-js && npm run build-styles && npm run build-test && npm run copy-fonts && npm run copy-assets"
```

I've been able to run the debugging console fine - that error you're getting makes sense if the sources content hasn't been built.

**Comment by paulovieira** [comment]
I don't remember the details about this error, but meanwhile I tried again the tv module in other project and it worked fine. I'm running node 0.10.40. So I'm not sure what was the problem, but seems to be something sporadic.
