### ISSUE TITLE
Allow Secure Web Sockets

### ISSUE THREAD

**Issue by Vatosteve** [hapijs/tv#108]
Our hapi server is configured for https and we get the following error when attempting to view the debug console: 

Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

Are there any plans to support secure web sockets?

**Comment by hueniverse** [comment]
This module needs people to help maintain it. If you want this feature your best chances are to add it yourself...

**Comment by rainabba** [comment]
@hueniverse Any information you can provide to kick-start that effort? I'm having the same issue and am not unfamiliar with WS on Node/Hapi so I'd be willing to give it a shot, but better to not waste hours trying to find out where to start :)

**Comment by hueniverse** [comment]
I haven't looked at the code in a while...

**Comment by hueniverse** [comment]
@geek should we fine a new lead maintainer for this?

**Comment by geek** [comment]
@hueniverse how did you read my mind like that ;)

I have been asking around, but no one is interested who I have asked.  Looks like I need to make that more public, I will file an issue.

**Comment by rainabba** [comment]
@geek Just curious, any ETA on this and are you looking for help still? I'm at a point where I'd really like to have this implemented.

**Comment by rainabba** [comment]
Looks like implementing SSL is just a matter of getting the right connection object through (with keys) and the change was simple, but I'm getting 404's on /debug/console so I can't confirm. I'm not seeing any other issues so I'm guessing that I'm just being dense.

**Comment by geek** [comment]
@rainabba I added a PR for the feature... its open at the moment

**Comment by rainabba** [comment]
@geek Thanks. Any update on this?
