### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by geek** [hapijs/tv#110]
Are you interested in maintaining `tv`, if so please comment and let me know.

**Comment by osukaa** [comment]
I would be interested! :)

**Comment by geek** [comment]
You got it!

Thanks.

**Comment by osukaa** [comment]
@geek that was fast! thanks

**Comment by geek** [comment]
You are now the owner on npm https://www.npmjs.com/~osukaa

Feel free to email me too and I can help you get up to speed.
