### ISSUE TITLE
Node v4.0.0 Compatability

### ISSUE THREAD

**Issue by drouillard** [hapijs/tv#119]
When installing I am running into issue with the ws dependency being out of date and depending on an old version of bufferutil which uses a non compatible version of node-gyp. node-gyp upgrade was one of the breaking changes.

    node_modules/tv/node_modules/ws/node_modules/bufferutil
    > node-gyp rebuild

    CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
    In file included from ../src/bufferutil.cc:16:
     ../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
     NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^

**Comment by Marsup** [comment]
@osukaa maybe it would help your maintenance to rely on nes ?

**Comment by osukaa** [comment]
I recently published the 4.1.2 version! Could you try if that helps with your issue @drouillard ?

**Comment by drouillard** [comment]
Updated version works for me. Thanks @osukaa.
