### ISSUE TITLE
state of tv

### ISSUE THREAD

**Issue by lloydbenson** [hapijs/tv#129]
I looked at this and for the most part it is falling behind on versions of modules and there are quite a few open issues.  @osukaa do you still maintain this module?

**Comment by osukaa** [comment]
@lloydbenson Hi! I'm trying but the last couple of months I haven't had any free time to work on this :/

**Comment by devinivy** [comment]
If you have time for code reviewing, maybe tacking help wanted labels on a few issues would be a nice compromise.

**Comment by osukaa** [comment]
@devinivy that's a good idea!

**Comment by osukaa** [comment]
@devinivy @lloydbenson I'm currently working on getting it to work with node 4 & 5 but I'm not yet done with the branch :/

**Comment by ugate** [comment]
@osukaa So, is it safe to presume that the current version is not compatible with node 4/5?

**Comment by osukaa** [comment]
@ugate right! sorry :/

**Comment by ugate** [comment]
@osukaa np... just the clarity I was :eyes: for. Thanks!
